### PR TITLE
Update README.md

### LINKED ISSUE #10: fix(README.md) Update installation process in README.md
# Lacus

A capturing system using playwright, as a web service.

### System dependencies

You need poetry installed, see the [install guide](https://python-poetry.org/docs/).

### Prerequisites

You need to have redis cloned and installed in the same directory you clone this template in:
this repository and `redis` must be in the same directory, and **not** `redis` cloned in this directory. See [this guide](https://www.lookyloo.eu/docs/main/install-lookyloo.html#_install_redis).

### Installation

Clone this repository:

```bash
git clone https://github.com/ail-project/lacus.git
```

From the directory you just cloned, run:

```bash
cd lacus
poetry install
```

Install the system dependencies required by playwright (will call sudo):

```bash
poetry shell 
playwright install-deps
```

Initialize the `.env` file:

```bash
echo LACUS_HOME="`pwd`" >> .env
```

Initialize the config and install playwright browsers:

```bash
poetry run update --init

* Restarting
Continue? (y/N) <-- N
Okay, quitting.
```

**Clone the Redis server:**

1. Navigate to the parent directory:

```bash
pushd ..
```

2. Clone the Redis repository:

```bash
git clone https://github.com/antirez/redis.git
```

3. Enter the Redis directory:

```bash
pushd redis
```

4. Checkout the version "7.0" of Redis:

```bash
git checkout 7.0
```

5. Compile Redis:

```bash
make
```

6. Return to the previous directory:

```bash
popd
```

7. Return to the initial directory:

```bash
popd
```

## start
- `poetry run start`: This command is used to start a Lacus service
```bash
poetry run start 
```
## stop
- `poetry run stop`: This command is used to stop a Lacus service
```bash
poetry run stop
```

## update
- `poetry run update`: This command is used to update the project dependencies according to the configurations defined in the `pyproject.toml` file.
```bash
poetry run update
```

## shutdown
- `poetry run shutdown`: This command is used to completely shut down a  Lacus service
```bash
poetry run shutdown 
```

## run_backend
- `poetry run run_backend`: This command is used to manager the backend redis 
```bash
poetry run run_backend --help 
  -h, --help  show this help message and exit
  --start     Start all
  --stop      Stop all
  --status    Show status
```
## start_website
- `poetry run start_website`: This command is used to start the web server 
```bash
poetry run start_website
```
## capture_manager
- `poetry run capture_manager`: This command is used to start the capture manager for data.
```bash
poetry run capture_manager
```

## stop_capture_manager
- `poetry run stop_capture_manager`: This command is used to stop the running capture manager.
```bash
poetry run stop_capture_manager
```

@Terrtia @SteveClement @adulau @Rafiot @gallypette

### PR DESCRIPTION
**Pull request by darkcode357**
# Description

This pull request aims to perform a documentation review

## Type of change

- [x] This change a documentation update

**Test Configuration**:
* Firmware version: 1.6.0
* Hardware: gitlab_runner
* features: all features passed to the gitlab_runner
* SDK: **python3.8,3.9,3.10,3.11**

# Checklist:
  - [x] **Fixed contents**: in  lacus/[README.md](https://github.com/ail-project/lacus/compare/main...darkcode357:lacus:main#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
  
# issues closed
close #10 

@Rafiot

### CODE REVIEW

**Comment by darkcode357** [comment]
please review @adulau @Rafiot @gallypette @SteveClement

**Comment by Rafiot** [comment]
I added a comment in the previous PR on that same file, you didn't implement them in this PR.

Whoever is behind this account, please review the changes your AI generates before asking us to do any kind of code review and merge the code.

In this one, the sections headers aren't even correct (you're using `##` before using `###`).

**Comment by darkcode357** [comment]
In moral, man, if you don't know how to differentiate an AI from a human being, there's no reason for me to try to help. I'm trying to contribute to the project, but you're being extremely rude to me.

I implemented the documentation in the readme, documented all the code, did a code review, pointed out points for improvement and was willing to help. However, due to your lack of consideration, politeness, and empathy for others, I am withdrawing from contributing to this project.

Honestly, I expected more from an intelligence center in dealing with people and following good practices in technical operations. At this point I am only referring to you as I don't know the other people involved.

**Comment by vncloudsco** [comment]
@Rafiot  Why not update the installation instructions? I felt terrible about the software's instructions and this one is really the solution , don't understand why it was rejected?

**Comment by adulau** [comment]
@vncloudsco  Indeed there are some good part with the back-end management which should be in the README.

**Comment by Rafiot** [comment]
It was rejected because most of the command listed there were wrong and should not be used (they're executed by `start.py` and having it in the readme was confusing)

What is missing in the readme? The install guide for redis in pointing to https://www.lookyloo.eu/docs/main/install-lookyloo.html#_install_redis and the rest of the install is in the readme.
I admit we could add the details for redis in the readme, but none of the rest is useful.

Can you please open a new issue describing the problems you're having?

**Pull request closed without merging**
